const {authUser,req:sbreq,json,profile}=require('./_lib');
const esc=v=>encodeURIComponent(String(v));
async function guard(req,res){const u=await authUser(req);if(!u){json(res,401,{error:'Login required'});return null}const p=await profile(u.id,'admin');if(!p){json(res,403,{error:'Admin only'});return null}return u}
async function audit(adminId,action,details){try{await sbreq('/rest/v1/admin_audit_logs',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({admin_id:adminId,action,details})})}catch(e){}}
async function userRows(){return sbreq('/rest/v1/user_profiles?select=*,user_accounts!inner(email,phone,created_at,blocked)&order=created_at.desc&limit=500')}
async function astroRows(){return sbreq('/rest/v1/astrologers?select=*&order=rank_position.asc.nullslast,rank_score.desc&limit=500')}
async function astroAppRows(){const rows=await sbreq('/rest/v1/astrologer_applications?select=*&order=created_at.desc&limit=500');const ids=[...new Set(rows.map(x=>x.user_id).filter(Boolean))];if(!ids.length)return rows.map(x=>({...x,profile:null}));const ac=await sbreq(`/rest/v1/astrologer_accounts?id=in.(${ids.map(esc).join(',')})&select=id,email,phone,full_name,blocked`);const m=new Map(ac.map(x=>[x.id,x]));return rows.map(x=>({...x,profile:m.get(x.user_id)||null}))}
async function decorateAstros(rows){const ids=rows.map(x=>x.id);const ac=ids.length?await sbreq(`/rest/v1/astrologer_accounts?id=in.(${ids.map(esc).join(',')})&select=id,email,phone,full_name,blocked`):[];const m=new Map(ac.map(x=>[x.id,x]));return rows.map(x=>{const a=m.get(x.id)||{};return {...x,full_name:x.full_name||a.full_name||'Astrologer',email:a.email||'',phone:a.phone||'',blocked:!!(x.blocked||a.blocked),role:'astrologer'}})}
module.exports=async(req,res)=>{try{const u=await guard(req,res);if(!u)return;const action=String(req.query?.action||'overview');
 if(req.method==='GET'&&action==='overview'){const [users,apps,astros,convs,reviews,kundalis,payments]=await Promise.all([sbreq('/rest/v1/user_profiles?select=id,blocked&limit=5000'),sbreq('/rest/v1/astrologer_applications?select=id,status&limit=5000'),sbreq('/rest/v1/astrologers?select=id,verified,online,last_seen&limit=5000'),sbreq('/rest/v1/conversations?select=id,status&limit=5000'),sbreq('/rest/v1/reviews?select=id,rating,moderation_status&limit=5000'),sbreq('/rest/v1/kundalis?select=id&limit=5000'),sbreq('/rest/v1/payments?select=id,status,amount&limit=5000')]);return json(res,200,{stats:{users:users.length,astrologers:astros.length,admins:(await sbreq('/rest/v1/admin_profiles?select=id&limit=5000')).length,blockedUsers:users.filter(x=>x.blocked).length,pendingApplications:apps.filter(x=>x.status==='pending').length,approvedAstrologers:astros.filter(x=>x.verified).length,onlineAstrologers:astros.filter(x=>x.online&&x.last_seen&&(Date.now()-new Date(x.last_seen).getTime()<=75000)).length,activeChats:convs.filter(x=>x.status==='accepted').length,totalChats:convs.length,totalReviews:reviews.length,pendingReviews:reviews.filter(x=>x.moderation_status==='pending').length,totalKundalis:kundalis.length,pendingPayments:payments.filter(x=>x.status==='pending').length,approvedPayments:payments.filter(x=>x.status==='approved').length,revenue:payments.filter(x=>x.status==='approved').reduce((s,x)=>s+Number(x.amount||0),0),pendingAmount:payments.filter(x=>x.status==='pending').reduce((s,x)=>s+Number(x.amount||0),0),refundedAmount:payments.filter(x=>x.status==='refunded').reduce((s,x)=>s+Number(x.amount||0),0),astrologerPayable:payments.filter(x=>x.status==='approved').reduce((s,x)=>s+Number(x.amount||0),0)}})}
 if(req.method==='GET'&&action==='users'){const q=String(req.query?.q||'').trim();const rows=await sbreq('/rest/v1/user_profiles?select=*&order=created_at.desc&limit=500');const ac=await sbreq('/rest/v1/user_accounts?select=id,email,phone,created_at,blocked&limit=500');const m=new Map(ac.map(x=>[x.id,x]));let users=rows.map(x=>({...x,...(m.get(x.id)||{}),role:'user'}));if(q){const z=q.toLowerCase();users=users.filter(x=>[x.full_name,x.email,x.phone].some(v=>String(v||'').toLowerCase().includes(z)))}return json(res,200,{users})}
 if(req.method==='GET'&&action==='applications')return json(res,200,{applications:await astroAppRows()});
 if(req.method==='GET'&&action==='astrologers')return json(res,200,{astrologers:await decorateAstros(await astroRows())});
 if(req.method==='GET'&&action==='conversations'){const rows=await sbreq('/rest/v1/conversations?select=*&order=created_at.desc&limit=500');const uids=[...new Set(rows.map(x=>x.user_id).filter(Boolean))],aids=[...new Set(rows.map(x=>x.astrologer_id).filter(Boolean))];const [ups,aas]=await Promise.all([uids.length?sbreq(`/rest/v1/user_profiles?id=in.(${uids.map(esc).join(',')})&select=id,full_name,avatar_url`):[],aids.length?sbreq(`/rest/v1/astrologers?id=in.(${aids.map(esc).join(',')})&select=id,full_name,avatar_url`):[]]);const um=new Map(ups.map(x=>[x.id,x])),am=new Map(aas.map(x=>[x.id,x]));return json(res,200,{conversations:rows.map(x=>({...x,user:um.get(x.user_id)||null,astrologer:am.get(x.astrologer_id)||null}))})}
 if(req.method==='GET'&&action==='reviews'){const rows=await sbreq('/rest/v1/reviews?select=*&order=created_at.desc&limit=500');return json(res,200,{reviews:rows})}
 if(req.method==='GET'&&action==='payments')return json(res,200,{payments:await sbreq('/rest/v1/payments?select=*&order=created_at.desc&limit=500')});
 if(req.method==='GET'&&action==='kundlis')return json(res,200,{kundalis:await sbreq('/rest/v1/kundalis?select=*&order=created_at.desc&limit=500')});
 if(req.method==='GET'&&action==='kundli'){const id=String(req.query?.id||'');if(!id)return json(res,400,{error:'id required'});const rows=await sbreq(`/rest/v1/kundalis?id=eq.${esc(id)}&select=*`);return json(res,200,{kundli:rows[0]||null})}
 if(req.method==='GET'&&action==='settings'){const rows=await sbreq('/rest/v1/platform_settings?select=key,value');const settings={};for(const r of rows)settings[r.key]=r.value;return json(res,200,{settings})}
 if(req.method==='GET'&&action==='audit')return json(res,200,{logs:await sbreq('/rest/v1/admin_audit_logs?select=*&order=created_at.desc&limit=300')});
 if(req.method==='GET'&&action==='messages'){const id=String(req.query?.conversation_id||'');if(!id)return json(res,400,{error:'conversation_id required'});return json(res,200,{messages:await sbreq(`/rest/v1/messages?conversation_id=eq.${esc(id)}&select=*&order=created_at.asc&limit=1000`)})}
 if(req.method==='PATCH'&&action==='settings'){const b=req.body||{},incoming=b.settings&&typeof b.settings==='object'?b.settings:{};for(const [key,value] of Object.entries(incoming)){await sbreq(`/rest/v1/platform_settings?key=eq.${esc(key)}`,{method:'DELETE'}).catch(()=>{});await sbreq('/rest/v1/platform_settings',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({key,value,updated_by:u.id,updated_at:new Date().toISOString()})})}await audit(u.id,'platform_settings_update',{keys:Object.keys(incoming)});return json(res,200,{ok:true})}
 if(req.method==='PATCH'&&action==='user'){const id=String(req.body?.user_id||'');if(!id)return json(res,400,{error:'user_id required'});const patch={};if('full_name'in req.body)patch.full_name=String(req.body.full_name||'');if('blocked'in req.body)patch.blocked=!!req.body.blocked;const rows=await sbreq(`/rest/v1/user_profiles?id=eq.${esc(id)}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify({...patch,updated_at:new Date().toISOString()})});if('blocked'in req.body)await sbreq(`/rest/v1/user_accounts?id=eq.${esc(id)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({blocked:!!req.body.blocked})});await audit(u.id,'user_update',{user_id:id,changes:patch});return json(res,200,{user:rows[0]||null})}
 if(req.method==='PATCH'&&action==='application'){const b=req.body||{},userId=String(b.user_id||''),status=String(b.status||'');if(!userId||!['approved','rejected'].includes(status))return json(res,400,{error:'Invalid application update'});const a=(await sbreq(`/rest/v1/astrologer_applications?user_id=eq.${esc(userId)}&select=*`))[0];if(!a)return json(res,404,{error:'Application not found'});const now=new Date().toISOString();if(status==='approved'){await sbreq(`/rest/v1/astrologer_accounts?id=eq.${esc(userId)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({approved:true})});await sbreq(`/rest/v1/astrologers?id=eq.${esc(userId)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({verified:true,approved_at:now,online:false})})}const rows=await sbreq(`/rest/v1/astrologer_applications?id=eq.${esc(a.id)}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify({status,admin_note:String(b.admin_note||''),updated_at:now})});await audit(u.id,'application_'+status,{application_id:a.id,user_id:userId});return json(res,200,{ok:true,application:rows[0]})}
 if(req.method==='PATCH'&&action==='astrologer'){const id=String(req.body?.astrologer_id||'');if(!id)return json(res,400,{error:'astrologer_id required'});const patch={};for(const k of ['bio','education','experience_years','expertise','languages','online','verified','chat_enabled','call_enabled','video_enabled','boosted'])if(k in req.body)patch[k]=req.body[k];if('fee'in req.body)patch.fee=Math.max(0,Number(req.body.fee)||0);if('discount'in req.body)patch.discount=Math.min(100,Math.max(0,Number(req.body.discount)||0));const rows=await sbreq(`/rest/v1/astrologers?id=eq.${esc(id)}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify({...patch,updated_at:new Date().toISOString()})});await audit(u.id,'astrologer_update',{astrologer_id:id,changes:patch});return json(res,200,{astrologer:rows[0]})}
 if(req.method==='PATCH'&&action==='payment'){const id=String(req.body?.payment_id||'');const status=['approved','rejected','refunded','pending'].includes(req.body?.status)?req.body.status:null;if(!id||!status)return json(res,400,{error:'Invalid payment update'});const patch={status,admin_note:String(req.body.admin_note||''),updated_at:new Date().toISOString()};if(status==='approved'){patch.approved_by=u.id;patch.approved_at=new Date().toISOString()}const rows=await sbreq(`/rest/v1/payments?id=eq.${esc(id)}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(patch)});return json(res,200,{payment:rows[0]})}
 if(req.method==='PATCH'&&action==='review'){const id=String(req.body?.review_id||'');const status=['pending','approved','hidden','flagged'].includes(req.body?.moderation_status)?req.body.moderation_status:'pending';const rows=await sbreq(`/rest/v1/reviews?id=eq.${esc(id)}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify({moderation_status:status,admin_note:String(req.body?.admin_note||'')})});return json(res,200,{review:rows[0]})}
 if(req.method==='PATCH'&&action==='conversation'){const id=String(req.body?.conversation_id||''),status=['requested','astrologer_accepted','accepted','rejected','missed','closed'].includes(req.body?.status)?req.body.status:null;if(!id||!status)return json(res,400,{error:'Invalid conversation update'});const rows=await sbreq(`/rest/v1/conversations?id=eq.${esc(id)}`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify({status,...(status==='closed'?{closed_at:new Date().toISOString()}: {})})});return json(res,200,{conversation:rows[0]})}
 return json(res,405,{error:'Method not allowed'})
}catch(e){return json(res,500,{error:e.message})}};
